
export const abpStepsTypes = {

    opinionStepOneList:        '[OPINION STEP ONE ABP] Opinion Step One List',
    opinionStepOneRemove:      '[OPINION STEP ONE ABP] Remove Opinion Step One List',
    opinionStepOneNew:         '[OPINION STEP ONE ABP] New Opinion Step One',
    opinionStepOneNewMany:     '[OPINION STEP ONE ABP] New Many Opinion Step One',
    opinionStepOneUpdate:      '[OPINION STEP ONE ABP] Update Opinion Step One',
    opinionStepOneBlock:       '[OPINION STEP ONE ABP] Block Opinion Step One',
    opinionStepOneLoad:        '[OPINION STEP ONE ABP] Opinion Step One Load',
    opinionStepOneStop:        '[OPINION STEP ONE ABP] Opinion Step One Stop',
    opinionStepOneNewCount:    '[OPINION STEP ONE ABP] Opinion Step One New Count',
    opinionStepOneRemoveCount: '[OPINION STEP ONE ABP] Opinion Step One Remove Count',
    // opinionStepOneDetailList:   '[OPINION STEP ONE ABP] Opinion Step One Detail List',
    // opinionStepOneDetailRemove: '[OPINION STEP ONE ABP] Remove Opinion Step One Detail List',
    // opinionStepOneDetailNew:    '[OPINION STEP ONE ABP] New Opinion Step One Detail List',
    // opinionStepOneDetailUpdate: '[OPINION STEP ONE ABP] Update Opinion Step One Detail List',

    interactionStepOneList:   '[INTERACTION STEP ONE ABP] Interaction Step One List',
    interactionStepOneRemove: '[INTERACTION STEP ONE ABP] Remove Interaction Step One List',
    // interactionStepOneNew:    '[INTERACTION STEP ONE ABP] New Interaction Step One',
    interactionStepOneUpdate: '[INTERACTION STEP ONE ABP] Update Interaction Step One',
    interactionStepOneBlock:  '[INTERACTION STEP ONE ABP] Block Interaction Step One',
    interactionStepOneLoad:   '[INTERACTION STEP ONE ABP] Interaction Step One Load',
    interactionStepOneStop:   '[INTERACTION STEP ONE ABP] Interaction Step One Stop',

    questionStepOneList:   '[QUESTION STEP ONE ABP] Question Step One List',
    questionStepOneRemove: '[QUESTION STEP ONE ABP] Remove Question Step One List',
    questionStepOneNew:    '[QUESTION STEP ONE ABP] New Question Step One',
    questionStepOneUpdate: '[QUESTION STEP ONE ABP] Update Question Step One',
    questionStepOneBlock:  '[QUESTION STEP ONE ABP] Block Question Step One',
    questionStepOneLoad:   '[QUESTION STEP ONE ABP] Question Step One Load',
    questionStepOneStop:   '[QUESTION STEP ONE ABP] Question Step One Stop',

    answerStepOneList:   '[ANSWER STEP ONE ABP] Answer Step One List',
    answerStepOneRemove: '[ANSWER STEP ONE ABP] Remove Answer Step One List',
    answerStepOneNew:    '[ANSWER STEP ONE ABP] New Answer Step One',
    answerStepOneUpdate: '[ANSWER STEP ONE ABP] Update Answer Step One',
    answerStepOneBlock:  '[ANSWER STEP ONE ABP] Block Answer Step One',
    answerStepOneLoad:   '[ANSWER STEP ONE ABP] Answer Step One Load',
    answerStepOneStop:   '[ANSWER STEP ONE ABP] Answer Step One Stop',

    studentIdeaStepTwoList:   '[STUDENT IDEA STEP TWO ABP] Student Idea Step Two List',
    studentIdeaStepTwoRemove: '[STUDENT IDEA STEP TWO ABP] Remove Student Idea Step Two List',
    studentIdeaStepTwoNew:    '[STUDENT IDEA STEP TWO ABP] New Student Idea Step Two',
    studentIdeaStepTwoBlock:  '[STUDENT IDEA STEP TWO ABP] Block Student Idea Step Two',
    studentIdeaStepTwoLoad:   '[STUDENT IDEA STEP TWO ABP] Student Idea Step Two Load',
    studentIdeaStepTwoStop:   '[STUDENT IDEA STEP TWO ABP] Student Idea Step Two Stop',

    rateStudentIdeaStepTwoList:   '[RATE STUDENT IDEA STEP TWO ABP] Rate Student Idea Step Two List',
    rateStudentIdeaStepTwoRemove: '[RATE STUDENT IDEA STEP TWO ABP] Remove Rate Student Idea Step Two List',
    rateStudentIdeaStepTwoUpdate: '[RATE STUDENT IDEA STEP TWO ABP] Update Rate Student Idea Step Two',
    rateStudentIdeaStepTwoLoad:   '[RATE STUDENT IDEA STEP TWO ABP] Rate Student Idea Step Two Load',
    rateStudentIdeaStepTwoStop:   '[RATE STUDENT IDEA STEP TWO ABP] Rate Student Idea Step Two Stop',

    learnedConceptStepThreeList:   '[LEARNED CONCEPT STEP THREE ABP] Learned Concept Step Three List',
    learnedConceptStepThreeRemove: '[LEARNED CONCEPT STEP THREE ABP] Remove Learned Concept Step Three List',
    learnedConceptStepThreeNew:    '[LEARNED CONCEPT STEP THREE ABP] New Learned Concept Step Three',
    learnedConceptStepThreeLoad:   '[LEARNED CONCEPT STEP THREE ABP] Learned Concept Step Three Load',
    learnedConceptStepThreeStop:   '[LEARNED CONCEPT STEP THREE ABP] Learned Concept Step Three Stop',
    learnedConceptStepThreeBlock:  '[LEARNED CONCEPT STEP THREE ABP] Block Learned Concept Step Three',
    
    learnedConceptReferenceStepThreeNew:    '[LEARNED CONCEPT REFERENCE STEP THREE ABP] New Learned Concept Reference Step Three',
    learnedConceptReferenceStepThreeBlock:  '[LEARNED CONCEPT REFERENCE STEP THREE ABP] Block Learned Concept Reference Step Three',

    unknownConceptStepFourList:           '[UNKNOWN CONCEPT STEP FOUR ABP] Unknown Concept Step Four List',
    unknownConceptStepFourRemove:         '[UNKNOWN CONCEPT STEP FOUR ABP] Remove Unknown Concept Step Four List',
    unknownConceptStepFourNew:            '[UNKNOWN CONCEPT STEP FOUR ABP] New Unknown Concept Step Four',
    unknownConceptStepFourLoad:           '[UNKNOWN CONCEPT STEP FOUR ABP] Unknown Concept Step Four Load',
    unknownConceptStepFourStop:           '[UNKNOWN CONCEPT STEP FOUR ABP] Unknown Concept Step Four Stop',
    unknownConceptStepFourBlock:          '[UNKNOWN CONCEPT STEP FOUR ABP] Block Unknown Concept Step Four',
    
    unknownConceptReferenceStepFourNew:   '[UNKNOWN CONCEPT REFERENCE STEP FOUR ABP] New Unknown Concept Reference Step Four',
    unknownConceptReferenceStepFourBlock: '[UNKNOWN CONCEPT REFERENCE STEP FOUR ABP] Block Unknown Concept Reference Step Four',

    performActionStepFiveList:       '[PERFORM ACTION STEP FIVE ABP] Perform Action Step Five List',
    performActionStepFiveRemove:     '[PERFORM ACTION STEP FIVE ABP] Remove Perform Action Step Five List',
    performActionStepFiveNew:        '[PERFORM ACTION STEP FIVE ABP] New Perform Action Step Five',
    performActionStepFiveBlock:      '[PERFORM ACTION STEP FIVE ABP] Block Perform Action Step Five',
    performActionStepFiveLoad:       '[PERFORM ACTION STEP FIVE ABP] Perform Action Step Five Load',
    performActionStepFiveStop:       '[PERFORM ACTION STEP FIVE ABP] Perform Action Step Five Stop',

    ratePerformActionStepFiveList:   '[RATE PERFORM ACTION STEP FIVE ABP] Rate Perform Action Step Five List',
    ratePerformActionStepFiveRemove: '[RATE PERFORM ACTION STEP FIVE ABP] Remove Rate Perform Action Step Five List',
    ratePerformActionStepFiveUpdate: '[RATE PERFORM ACTION STEP FIVE ABP] Update Rate Perform Action Step Five',
    ratePerformActionStepFiveLoad:   '[RATE PERFORM ACTION STEP FIVE ABP] Rate Perform Action Step Five Load',
    ratePerformActionStepFiveStop:   '[RATE PERFORM ACTION STEP FIVE ABP] Rate Perform Action Step Five Stop',

    problemDefinitionStepSixList:           '[PROBLEM DEFINITION STEP SIX ABP] Problem Definition Step Six List',
    problemDefinitionStepSixRemove:         '[PROBLEM DEFINITION STEP SIX ABP] Remove Problem Definition Step Six List',
    problemDefinitionStepSixNew:            '[PROBLEM DEFINITION STEP SIX ABP] New Problem Definition Step Six',
    problemDefinitionStepSixUpdate:         '[PROBLEM DEFINITION STEP SIX ABP] Update Problem Definition Step Six',
    problemDefinitionStepSixBlock:          '[PROBLEM DEFINITION STEP SIX ABP] Block Problem Definition Step Six',
    problemDefinitionStepSixLoad:           '[PROBLEM DEFINITION STEP SIX ABP] Problem Definition Step Six Load',
    problemDefinitionStepSixStop:           '[PROBLEM DEFINITION STEP SIX ABP] Problem Definition Step Six Stop',

    problemDefinitionReferenceStepSixBlock: '[PROBLEM DEFINITION REFERENECE STEP SIX ABP] Block Problem Definition Reference Step Six',
    problemDefinitionReferenceStepSixNew:   '[PROBLEM DEFINITION REFERENECE STEP SIX ABP] New Problem Definition Reference Step Six',

    getInformationStepSevenList:            '[GET INFORMATION STEP SEVEN ABP] Get Information Step Seven List',
    getInformationStepSevenRemove:          '[GET INFORMATION STEP SEVEN ABP] Remove Get Information Step Seven List',
    getInformationStepSevenNew:             '[GET INFORMATION STEP SEVEN ABP] New Get Information Step Seven',
    getInformationStepSevenUpdate:          '[GET INFORMATION STEP SEVEN ABP] Update Get Information Step Seven',
    getInformationStepSevenLoad:            '[GET INFORMATION STEP SEVEN ABP] Get Information Step Seven Load',
    getInformationStepSevenStop:            '[GET INFORMATION STEP SEVEN ABP] Get Information Step Seven Stop',

    informationReferenceStepSevenBlock:     '[INFORMATION REFERENECE STEP SEVEN ABP] Block Information Reference Step Seven',
    informationReferenceStepSevenNew:       '[INFORMATION REFERENECE STEP SEVEN ABP] New Information Reference Step Seven',

    problemResolutionStepEightList:         '[PROBLEM RESOLUTION STEP EIGHT ABP] Problem Resolution Step Eight List',
    problemResolutionStepEightRemove:       '[PROBLEM RESOLUTION STEP EIGHT ABP] Remove Problem Resolution Step Eight List',
    problemResolutionStepEightNew:          '[PROBLEM RESOLUTION STEP EIGHT ABP] New Problem Resolution Step Eight',
    problemResolutionStepEightUpdate:       '[PROBLEM RESOLUTION STEP EIGHT ABP] Update Problem Resolution Step Eight',
    problemResolutionStepEightLoad:         '[PROBLEM RESOLUTION STEP EIGHT ABP] Problem Resolution Step Eight Load',
    problemResolutionStepEightStop:         '[PROBLEM RESOLUTION STEP EIGHT ABP] Problem Resolution Step Eight Stop',

}