
export const acMethodologyTypes = {
    
    acList:                      '[AC] Ac List',
    acRemove:                    '[AC] Remove Ac',
    acNew:                       '[AC] New Ac',
    acUpdate:                    '[AC] Update Ac',
    acDelete:                    '[AC] Delete Ac',
    acBlock:                     '[AC] Block Ac',
    acLoad:                      '[AC] Ac Load',
    acStop:                      '[AC] Ac Stop',
    currentAcRemove:             '[AC] Remove Current Ac',

    teamAcList:                 '[TEAM AC] Team Ac List',
    teamAcRemove:               '[TEAM AC] Remove Team Ac List',
    teamAcNew:                  '[TEAM AC] New Team Ac',
    teamAcBlock:                '[TEAM AC] Block Team Ac',
    teamAcLoad:                 '[TEAM AC] Team Ac Load',
    teamAcStop:                 '[TEAM AC] Team Ac Stop',
    teamAcSetFinished:          '[TEAM AC] Team Ac Set Finished',
    teamAcRemoveFinished:       '[TEAM AC] Team Ac Remove Finished',
    teamDetailAcLoad:           '[TEAM AC] Team Detail Ac Load',
    teamDetailAcStop:           '[TEAM AC] Team Detail Ac Stop',
    teamDetailAcList:           '[TEAM AC] Team Detail Ac List',
    teamDetailAcRemove:         '[TEAM AC] Remove Team Detail Ac List',
    teamDetailAcNew:            '[TEAM AC] Team Detail Ac New',
    teamDetailAcBlock:          '[TEAM AC] Team Detail Ac Block',
    teamDetailAcUserNew:        '[TEAM AC] Team Detail Ac New User Ac',
    teamDetailAcUserRemove:     '[TEAM AC] Team Detail Ac Remove User Ac',

    rubricAcList:               '[RUBRIC AC] Rubric Ac List',
    rubricAcRemove:             '[RUBRIC AC] Remove Rubric Ac List',
    rubricAcNew:                '[RUBRIC AC] New Rubric Ac',
    rubricAcUpdate:             '[RUBRIC AC] Update Rubric Ac',
    rubricAcBlock:              '[RUBRIC AC] Block Rubric Ac',
    rubricAcLoad:               '[RUBRIC AC] Rubric Ac Load',
    rubricAcStop:               '[RUBRIC AC] Rubric Ac Stop',
    rubricDetailAcLoad:         '[RUBRIC AC] Rubric Detail Ac Load',
    rubricDetailAcStop:         '[RUBRIC AC] Rubric Detail Ac Stop',
    rubricDetailAcList:         '[RUBRIC AC] Rubric Detail Ac List',
    rubricDetailAcRemove:       '[RUBRIC AC] Remove Rubric Detail Ac List',
    rubricDetailAcNew:          '[RUBRIC AC] Rubric Detail Ac New',
    rubricDetailAcUpdate:       '[RUBRIC AC] Rubric Detail Ac Update',
    rubricDetailAcBlock:        '[RUBRIC AC] Rubric Detail Ac Block',

    evaluationAcList:           '[EVALUATION AC] Evaluation Ac List',
    evaluationAcRemove:         '[EVALUATION AC] Remove Evaluation Ac List',
    evaluationAcNew:            '[EVALUATION AC] New Evaluation Ac',
    evaluationAcUpdate:         '[EVALUATION AC] Evaluation Ac Update',
    evaluationAcBlock:          '[EVALUATION AC] Block Evaluation Ac',
    evaluationAcLoad:           '[EVALUATION AC] Evaluation Ac Load',
    evaluationAcStop:           '[EVALUATION AC] Evaluation Ac Stop',
    evaluationDetailAcLoad:     '[EVALUATION AC] Evaluation Detail Ac Load',
    evaluationDetailAcStop:     '[EVALUATION AC] Evaluation Detail Ac Stop',
    evaluationDetailAcList:     '[EVALUATION AC] Evaluation Detail Ac List',
    evaluationDetailAcRemove:   '[EVALUATION AC] Remove Evaluation Detail Ac List',
    evaluationDetailAcNew:      '[EVALUATION AC] Evaluation Detail Ac New',
    evaluationDetailAcBlock:    '[EVALUATION AC] Evaluation Detail Ac Block',
}