
export const acRolesTypes = {

    acCoordinatorStrategyList:                 '[AC ROLES] Ac Coordinator Strategy List',
    acCoordinatorStrategyRemove:               '[AC ROLES] Remove Coordinator Strategy Ac',
    acCoordinatorStrategyNew:                  '[AC ROLES] New Coordinator Strategy Ac',
    acCoordinatorStrategyBlock:                '[AC ROLES] Block Coordinator Strategy Ac',
    acCoordinatorStrategyLoad:                 '[AC ROLES] Ac Coordinator Strategy Load',
    acCoordinatorStrategyStop:                 '[AC ROLES] Ac Coordinator Strategy Stop',

    acMemberPerformanceCoordinatorList:        '[AC ROLES] Ac Member Performance Coordinator List',
    acMemberPerformanceCoordinatorRemove:      '[AC ROLES] Remove Member Performance Coordinator Ac',
    acMemberPerformanceCoordinatorNew:         '[AC ROLES] New Member Performance Coordinator Ac',
    acMemberPerformanceCoordinatorBlock:       '[AC ROLES] Block Member Performance Coordinator Ac',
    acMemberPerformanceCoordinatorLoad:        '[AC ROLES] Ac Member Performance Coordinator Load',
    acMemberPerformanceCoordinatorStop:        '[AC ROLES] Ac Member Performance Coordinator Stop',

    acProblemResolutionGroupList:              '[AC ROLES] Ac Problem Resolution Group List',
    acProblemResolutionGroupRemove:            '[AC ROLES] Remove Problem Resolution Group Ac',
    acProblemResolutionGroupNew:               '[AC ROLES] New Problem Resolution Group Ac',
    acProblemResolutionGroupLoad:              '[AC ROLES] Ac Problem Resolution Group Load',
    acProblemResolutionGroupStop:              '[AC ROLES] Ac Problem Resolution Group Stop',
    
    acOrganizerActionList:                     '[AC ROLES] Ac Organizer Action List',
    acOrganizerActionRemove:                   '[AC ROLES] Remove Organizer Action Ac',
    acOrganizerActionNew:                      '[AC ROLES] New Organizer Action Ac',
    acOrganizerActionBlock:                    '[AC ROLES] Block Organizer Action Ac',
    acOrganizerActionLoad:                     '[AC ROLES] Ac Organizer Action Load',
    acOrganizerActionStop:                     '[AC ROLES] Ac Organizer Action Stop',

    acAssignActivityOrganizerList:             '[AC ROLES] Ac Assign Activity Organizer List',
    acAssignActivityOrganizerRemove:           '[AC ROLES] Remove Assign Activity Organizer Ac',
    acAssignActivityOrganizerNew:              '[AC ROLES] New Assign Activity Organizer Ac',
    acAssignActivityOrganizerBlock:            '[AC ROLES] Block Assign Activity Organizer Ac',
    acAssignActivityOrganizerLoad:             '[AC ROLES] Ac Assign Activity Organizer Load',
    acAssignActivityOrganizerStop:             '[AC ROLES] Ac Assign Activity Organizer Stop',
    
    acDescribeUnderstandingOrganizerList:      '[AC ROLES] Ac Describe Understanding Organizer List',
    acDescribeUnderstandingOrganizerRemove:    '[AC ROLES] Remove Describe Understanding Organizer Ac',
    acDescribeUnderstandingOrganizerNew:       '[AC ROLES] New Describe Understanding Organizer Ac',
    acDescribeUnderstandingOrganizerBlock:     '[AC ROLES] Block Describe Understanding Organizer Ac',
    acDescribeUnderstandingOrganizerLoad:      '[AC ROLES] Ac Describe Understanding Organizer Load',
    acDescribeUnderstandingOrganizerStop:      '[AC ROLES] Ac Describe Understanding Organizer Stop',
    
    acSpokesmanQuestionList:                   '[AC ROLES] Ac Spokesman Question List',
    acSpokesmanQuestionRemove:                 '[AC ROLES] Remove Spokesman Question Ac',
    acSpokesmanQuestionNew:                    '[AC ROLES] New Spokesman Question Ac',
    acSpokesmanQuestionBlock:                  '[AC ROLES] Block Spokesman Question Ac',
    acSpokesmanQuestionLoad:                   '[AC ROLES] Ac Spokesman Question Load',
    acSpokesmanQuestionStop:                   '[AC ROLES] Ac Spokesman Question Stop',
    
    acActivityDescriptionSpokesmanList:        '[AC ROLES] Ac Activity Description Spokesman List',
    acActivityDescriptionSpokesmanRemove:      '[AC ROLES] Remove Activity Description Spokesman Ac',
    acActivityDescriptionSpokesmanNew:         '[AC ROLES] New Activity Description Spokesman Ac',
    acActivityDescriptionSpokesmanBlock:       '[AC ROLES] Block Activity Description Spokesman Ac',
    acActivityDescriptionSpokesmanLoad:        '[AC ROLES] Ac Activity Description Spokesman Load',
    acActivityDescriptionSpokesmanStop:        '[AC ROLES] Ac Activity Description Spokesman Stop',
    
    acPerformanceDescriptionSpokesmanList:     '[AC ROLES] Ac Performance Description Spokesman List',
    acPerformanceDescriptionSpokesmanRemove:   '[AC ROLES] Remove Performance Description Spokesman Ac',
    acPerformanceDescriptionSpokesmanNew:      '[AC ROLES] New Performance Description Spokesman Ac',
    acPerformanceDescriptionSpokesmanLoad:     '[AC ROLES] Ac Performance Description Spokesman Load',
    acPerformanceDescriptionSpokesmanStop:     '[AC ROLES] Ac Performance Description Spokesman Stop',
 
    acSecretaryInformationList:                '[AC ROLES] Ac Secretary Information List',
    acSecretaryInformationRemove:              '[AC ROLES] Remove Secretary Information Ac',
    acSecretaryInformationNew:                 '[AC ROLES] New Secretary Information Ac',
    acSecretaryInformationBlock:               '[AC ROLES] Block Secretary Information Ac',
    acSecretaryInformationLoad:                '[AC ROLES] Ac Secretary Information Load',
    acSecretaryInformationStop:                '[AC ROLES] Ac Secretary Information Stop',
    
    acFeaturedInformationSecretaryList:        '[AC ROLES] Ac Featured Information Secretary List',
    acFeaturedInformationSecretaryRemove:      '[AC ROLES] Remove Featured Information Secretary Ac',
    acFeaturedInformationSecretaryNew:         '[AC ROLES] New Featured Information Secretary Ac',
    acFeaturedInformationSecretaryBlock:       '[AC ROLES] Block Featured Information Secretary Ac',
    acFeaturedInformationSecretaryLoad:        '[AC ROLES] Ac Featured Information Secretary Load',
    acFeaturedInformationSecretaryStop:        '[AC ROLES] Ac Featured Information Secretary Stop',
    
    acTeacherAnswerList:                       '[AC ROLES] Ac Teacher Answer List',
    acTeacherAnswerRemove:                     '[AC ROLES] Remove Teacher Answer Ac',
    acTeacherAnswerNew:                        '[AC ROLES] New Teacher Answer Ac',
    acTeacherAnswerBlock:                      '[AC ROLES] Block Teacher Answer Ac',
    acTeacherAnswerLoad:                       '[AC ROLES] Ac Teacher Answer Load',
    acTeacherAnswerStop:                       '[AC ROLES] Ac Teacher Answer Stop',
    
    acTeacherAnswerDescriptionSecretaryList:   '[AC ROLES] Ac Teacher Answer Description Secretary List',
    acTeacherAnswerDescriptionSecretaryRemove: '[AC ROLES] Remove Teacher Answer Description Secretary Ac',
    acTeacherAnswerDescriptionSecretaryNew:    '[AC ROLES] New Teacher Answer Description Secretary Ac',
    acTeacherAnswerDescriptionSecretaryBlock:  '[AC ROLES] Block Teacher Answer Description Secretary Ac',
    acTeacherAnswerDescriptionSecretaryLoad:   '[AC ROLES] Ac Teacher Answer Description Secretary Load',
    acTeacherAnswerDescriptionSecretaryStop:   '[AC ROLES] Ac Teacher Answer Description Secretary Stop',
    
}