
export const methodologyTypes = {

    duaList:                     '[DUA] Dua List',
    duaRemove:                   '[DUA] Remove Dua List',
    duaNew:                      '[DUA] New Dua',
    duaUpdate:                   '[DUA] Update Dua',
    duaDelete:                   '[DUA] Delete Dua',
    duaBlock:                    '[DUA] Block Dua',
    duaLoad:                     '[DUA] Dua Load',
    duaStop:                     '[DUA] Dua Stop',
    duaDetailList:               '[DUA] Dua Detail List',
    duaDetailRemove:             '[DUA] Remove Dua Detail List',
    duaDetailNew:                '[DUA] Dua Detail New',
    duaDetailDelete:             '[DUA] Dua Detail Delete',
    currentDuaRemove:            '[DUA] Remove Current Dua',

    activityList:                '[ACTIVITY] Activity List',
    activityRemove:              '[ACTIVITY] Remove Activity List',
    activityCurrentList:         '[ACTIVITY] CurrentActivity List',
    activityCurrentRemove:       '[ACTIVITY] Remove Current Activity List',
    activityNew:                 '[ACTIVITY] New Activity',
    activityUpdate:              '[ACTIVITY] Update Activity',
    activityDelete:              '[ACTIVITY] Delete Activity',
    activityLoad:                '[ACTIVITY] Activity Load',
    activityStop:                '[ACTIVITY] Activity Stop',
    activityDetailList:          '[ACTIVITY] Activity Detail List',
    activityDetailRemove:        '[ACTIVITY] Remove Activity Detail List',
    activityDetailNew:           '[ACTIVITY] New Activity Detail',
    activityDetailUpdate:        '[ACTIVITY] Update Activity Detail',
    activityDetailDelete:        '[ACTIVITY] Delete Activity Detail',
    
    studentActivityList:         '[STUDENT ACTIVITY] Student Activity List',
    studentActivityRemove:       '[STUDENT ACTIVITY] Remove Student Activity List',
    studentActivityNew:          '[STUDENT ACTIVITY] New Student Activity',
    studentActivityUpdate:       '[STUDENT ACTIVITY] Update Student Activity',
    studentActivityDelete:       '[STUDENT ACTIVITY] Delete Student Activity',
    studentActivityBlock:        '[STUDENT ACTIVITY] Block Student Activity',
    studentActivityLoad:         '[STUDENT ACTIVITY] Student Activity Load',
    studentActivityStop:         '[STUDENT ACTIVITY] Student Activity Stop',
    studentActivityDetailList:   '[STUDENT ACTIVITY] Student Activity Detail List',
    studentActivityDetailRemove: '[STUDENT ACTIVITY] Remove Student Activity Detail List',
    studentActivityDetailNew:    '[STUDENT ACTIVITY] New Student Activity Detail',
    studentActivityDetailUpdate: '[STUDENT ACTIVITY] Update Student Activity Detail',
    studentActivityDetailBlock:  '[STUDENT ACTIVITY] Block Student Activity Detail',
    studentActivitySetActive:    '[STUDENT ACTIVITY] Student Activity Active',
    studentActivitySetInactive:  '[STUDENT ACTIVITY] Student Activity Inactive',

    abpList:                     '[ABP] Abp List',
    abpRemove:                   '[ABP] Remove Abp',
    abpNew:                      '[ABP] New Abp',
    abpUpdate:                   '[ABP] Update Abp',
    abpDelete:                   '[ABP] Delete Abp',
    abpLoad:                     '[ABP] Abp Load',
    abpStop:                     '[ABP] Abp Stop',
    currentAbpRemove:            '[ABP] Remove Current Abp',

    teamAbpList:                 '[TEAM ABP] Team Abp List',
    teamAbpRemove:               '[TEAM ABP] Remove Team Abp List',
    teamAbpNew:                  '[TEAM ABP] New Team Abp',
    teamAbpUpdate:               '[TEAM ABP] Update Team Abp',
    teamAbpDelete:               '[TEAM ABP] Delete Team Abp',
    teamAbpLoad:                 '[TEAM ABP] Team Abp Load',
    teamAbpStop:                 '[TEAM ABP] Team Abp Stop',
    teamAbpNextStep:             '[TEAM ABP] Team Abp Next Step',
    teamDetailAbpList:           '[TEAM ABP] Team Abp Detail List',
    teamDetailAbpRemove:         '[TEAM ABP] Remove Team Abp Detail List',
    teamDetailAbpNew:            '[TEAM ABP] Team Abp Detail New',
    teamDetailAbpUpdate:         '[TEAM ABP] Team Abp Detail Update',
    teamDetailAbpBlock:          '[TEAM ABP] Team Abp Detail Block',

    rubricAbpList:               '[RUBRIC ABP] Rubric Abp List',
    rubricAbpRemove:             '[RUBRIC ABP] Remove Rubric Abp List',
    rubricAbpNew:                '[RUBRIC ABP] New Rubric Abp',
    rubricAbpUpdate:             '[RUBRIC ABP] Update Rubric Abp',
    rubricAbpDelete:             '[RUBRIC ABP] Delete Rubric Abp',
    rubricAbpLoad:               '[RUBRIC ABP] Rubric Abp Load',
    rubricAbpStop:               '[RUBRIC ABP] Rubric Abp Stop',
    rubricDetailAbpList:         '[RUBRIC ABP] Rubric Abp Detail List',
    rubricDetailAbpRemove:       '[RUBRIC ABP] Remove Rubric Abp Detail List',
    rubricDetailAbpNew:          '[RUBRIC ABP] Rubric Abp Detail New',
    rubricDetailAbpUpdate:       '[RUBRIC ABP] Rubric Abp Detail Update',
    rubricDetailAbpBlock:        '[RUBRIC ABP] Rubric Abp Detail Block',

    evaluationAbpList:           '[EVALUATION ABP] Evaluation Abp List',
    evaluationAbpRemove:         '[EVALUATION ABP] Remove Evaluation Abp List',
    evaluationAbpNew:            '[EVALUATION ABP] New Evaluation Abp',
    evaluationAbpUpdate:         '[EVALUATION ABP] Update Evaluation Abp',
    evaluationAbpDelete:         '[EVALUATION ABP] Delete Evaluation Abp',
    evaluationAbpLoad:           '[EVALUATION ABP] Evaluation Abp Load',
    evaluationAbpStop:           '[EVALUATION ABP] Evaluation Abp Stop',
    evaluationDetailAbpLoad:     '[EVALUATION ABP] Evaluation Detail Abp Load',
    evaluationDetailAbpStop:     '[EVALUATION ABP] Evaluation Detail Abp Stop',
    evaluationDetailAbpList:     '[EVALUATION ABP] Evaluation Abp Detail List',
    evaluationDetailAbpRemove:   '[EVALUATION ABP] Remove Evaluation Abp Detail List',
    evaluationDetailAbpNew:      '[EVALUATION ABP] Evaluation Abp Detail New',
    evaluationDetailAbpBlock:    '[EVALUATION ABP] Evaluation Abp Detail Block',

}