
export const types = {
    
    login:                        '[AUTH] Login',
    logout:                       '[AUTH] Logout',
    checkingFinish:               '[AUTH] Checking Finish',
    setIsUsernameValid:           '[AUTH] Set Is Username Valid',
    clearIsUsernameValid:         '[AUTH] Clear Is Username Valid',

    dashboardAdmin:               '[DASHBOARD] Load Admin Data',
    dashboardTeacher:             '[DASHBOARD] Load Teacher Data',
    dashboardStudent:             '[DASHBOARD] Load Student Data ',
    
    newError:                     '[UI] New Error',
    removeError:                  '[UI] Remove Error',
    newMessage:                   '[UI] New Message',
    removeMessage:                '[UI] Remove Message',
    openAdmin:                    '[UI] Open Admin',
    closeAdmin:                   '[UI] Close Admin',
    setSchoolPeriod:              '[UI] Set School Period',
    removeSchoolPeriod:           '[UI] Remove School Period',
    uiLoad:                       '[UI] Ui Load',
    uiStop:                       '[UI] Ui Stop',
    uiMessagesList:               '[UI] Ui Messages Conversations List',
    uiMessagesRemove:             '[UI] Ui Messages Conversations Remove',
    uiSpeedDialList:              '[UI] Ui Set Speed Dial List',
    uiSpeedDialRemove:            '[UI] Ui Remove Speed Dial List',
    uiSetChangeUserPass:          '[UI] Ui Set Change User Password',
    uiRemoveChangeUserPass:       '[UI] Ui Remove Change User Password',

    adminList:                    '[ADMIN] Admin List',
    adminRemove:                  '[ADMIN] Remove Admin',
    adminNew:                     '[ADMIN] New Admin',
    adminUpdate:                  '[ADMIN] Update Admin',
    adminDelete:                  '[ADMIN] Delete Admin',
    adminLoad:                    '[ADMIN] Admin Load',
    adminStop:                    '[ADMIN] Admin Stop',
    
    studentList:                  '[STUDENT] Students List',
    studentRemove:                '[STUDENT] Remove Students',
    studentNew:                   '[STUDENT] New Student',
    studentUpdate:                '[STUDENT] Update Student',
    studentDelete:                '[STUDENT] Delete Student',
    studentsDelete:               '[STUDENT] Delete Students',
    studentLoad:                  '[STUDENT] Student Load',
    studentStop:                  '[STUDENT] Student Stop',
  
    teacherList:                  '[TEACHER] Teachers List',
    teacherRemove:                '[TEACHER] Remove Teachers',
    teacherNew:                   '[TEACHER] New Teacher',
    teacherUpdate:                '[TEACHER] Update Teacher',
    teacherDelete:                '[TEACHER] Delete Teacher',
    teachersDelete:               '[TEACHER] Delete Teachers',
    teacherLoad:                  '[TEACHER] Teacher Load',
    teacherStop:                  '[TEACHER] Teacher Stop',
  
    areaList:                     '[AREA] Areas List',
    areaRemove:                   '[AREA] Remove Areas',
    areaNew:                      '[AREA] New Area',
    areaUpdate:                   '[AREA] Update Area',
    areaDelete:                   '[AREA] Delete Area',
    areasDelete:                  '[AREA] Delete Areas',
    areaLoad:                     '[AREA] Area Load',
    areaStop:                     '[AREA] Area Stop',
    coordinatorList:              '[AREA] Coordinators List',
    coordinatorRemove:            '[AREA] Remove Coordinators',
    areaTeacherList:              '[AREA] Teacher Area List',
    areaTeacherUpdate:            '[AREA] Update Teacher Area',
    areaTeacherRemove:            '[AREA] Remove Area Teachers',
    
    asignaturesList:              '[ASIGNATURE] Asignatures List',
    asignatureRemove:             '[ASIGNATURE] Remove Asignatures',
    asignatureNew:                '[ASIGNATURE] New Asignatures',
    asignatureUpdate:             '[ASIGNATURE] Update Asignatures',
    asignatureDelete:             '[ASIGNATURE] Delete Asignature',
    asignaturesDelete:            '[ASIGNATURE] Delete Asignatures',
    asignatureLoad:               '[ASIGNATURE] Asignatures Load',
    asignatureStop:               '[ASIGNATURE] Asignatures Stop',
    asignatureAreaList:           '[ASIGNATURE] Area Asignature List',
    asignatureAreaRemove:         '[ASIGNATURE] Remove Area Asignature',
    asignatureClassroomList:      '[ASIGNATURE] Classroom Asignature List',
    asignatureClassroomRemove:    '[ASIGNATURE] Remove Classroom Asignature',
    asignatureTeacherList:        '[ASIGNATURE] Teacher Asignature List',
    asignatureTeacherRemove:      '[ASIGNATURE] Remove Teacher Asignature',
    asignaturesDetailList:        '[ASIGNATURE] Asignatures Detail List',
    asignaturesDetailRemove:      '[ASIGNATURE] Remove Asignatures Detail',
    asignatureDetailNew:          '[ASIGNATURE] New Asignature Detail',
    asignatureDetailDelete:       '[ASIGNATURE] Delete Asignature Detail',

    schoolPeriodsList:            '[SCHOOLPERIOD] School Periods List',
    schoolPeriodsRemove:          '[SCHOOLPERIOD] Remove School Periods',
    schoolPeriodNew:              '[SCHOOLPERIOD] New School Period',
    schoolPeriodUpdate:           '[SCHOOLPERIOD] Update School Period',
    schoolPeriodDelete:           '[SCHOOLPERIOD] Delete School Period',
    schoolPeriodsDelete:          '[SCHOOLPERIOD] Delete School Periods',
    schoolPeriodLoad:             '[SCHOOLPERIOD] School Period Load',
    schoolPeriodStop:             '[SCHOOLPERIOD] School Period Stop',

    classroomsList:               '[CLASSROOM] Classrooms List',
    classroomsRemove:             '[CLASSROOM] Remove Classrooms',
    classroomNew:                 '[CLASSROOM] New Classroom Period',
    classroomUpdate:              '[CLASSROOM] Update Classroom Period',
    classroomDelete:              '[CLASSROOM] Delete Classroom Period',
    classroomsDelete:             '[CLASSROOM] Delete Classrooms',
    classroomLoad:                '[CLASSROOM] Classroom Load',
    classroomStop:                '[CLASSROOM] Classroom Stop',
    classroomSchoolPeriodList:    '[CLASSROOM] Classroom School Period List',
    classroomSchoolPeriodRemove:  '[CLASSROOM] Remove Classroom School Period',
    classroomDetailList:          '[CLASSROOM] Classroom Detail List',
    classroomDetailRemove:        '[CLASSROOM] Remove Classroom Detail',
    classroomDetailUpdate:        '[CLASSROOM] Update Classroom Detail',
    classroomDetailDelete:        '[CLASSROOM] Delete Classroom Detail',

    topicsList:                   '[TOPIC] Topics List',
    topicsRemove:                 '[TOPIC] Remove Topics',
    topicBlock:                   '[TOPIC] Block Topic',
    topicUpdate:                  '[TOPIC] Update Topic',
    topicDelete:                  '[TOPIC] Delete Topic',
    topicsDelete:                 '[TOPIC] Delete Topics',
    topicLoad:                    '[TOPIC] Topic Load',
    topicStop:                    '[TOPIC] Topic Stop',
    topicStudentsList:            '[TOPIC] Topic Students List',
    topicStudentsRemove:          '[TOPIC] Remove Topic Students',
    topicStudentsUpdate:          '[TOPIC] Update Topics Students',
    currentTopicNew:              '[TOPIC] New Current Topic',
    currentTopicRemove:           '[TOPIC] Current Topic Remove',
    currentMethodologyNew:        '[TOPIC] Load Current Methodology',
    currentMethodologyRemove:     '[TOPIC] Remove Current Methodology',
    currentMethodologyLoad:       '[TOPIC] Current Methodology Load',
    currentMethodologyStop:       '[TOPIC] Current Methodology Stop',
    
    glossariesList:               '[GLOSSARY] Glossary List',
    glossariesRemove:             '[GLOSSARY] Remove Glossaries',
    glossaryNew:                  '[GLOSSARY] New Glossary',
    glossaryUpdate:               '[GLOSSARY] Update Glossary',
    glossaryDelete:               '[GLOSSARY] Delete Glossary',
    glossaryLoad:                 '[GLOSSARY] Glossary Load',
    glossaryStop:                 '[GLOSSARY] Glossary Stop',
    glossariesDetailList:         '[GLOSSARY] Glossaries Detail List',
    glossariesDetailRemove:       '[GLOSSARY] Remove Glossaries Detail',
    glossaryDetailUpdate:         '[GLOSSARY] Glossary Detail',
    glossaryDetailDelete:         '[GLOSSARY] Delete Glossary Detail',
    glossariesDetailDelete:       '[GLOSSARY] Delete Glossaries Detail',

    conversationsList:            '[CONVERSATION] Conversations List',
    conversationsRemove:          '[CONVERSATION] Remove Conversations',
    conversationNew:              '[CONVERSATION] New Conversation',
    conversationBlock:            '[CONVERSATION] Block Conversation',
    conversationLoad:             '[CONVERSATION] Conversation Load',
    conversationStop:             '[CONVERSATION] Conversation Stop',
    conversationDetailLoad:       '[CONVERSATION] Conversation Detail Load',
    conversationDetailStop:       '[CONVERSATION] Conversation Detail Stop',
    conversationDetailList:       '[CONVERSATION] Conversation Detail List',
    conversationDetailRemove:     '[CONVERSATION] Remove Conversation Detail',
    currentConversationGet:       '[CONVERSATION] Current Conversation Get',
    currentConversationRemove:    '[CONVERSATION] Remove Current Conversation',
    conversationDetailNew:        '[CONVERSATION] New Conversation Detail',
    conversationDetailBlock:      '[CONVERSATION] Block Conversation Detail',
    conversationUsersList:        '[CONVERSATION] Conversation Users List',
    conversationUsersRemove:      '[CONVERSATION] Remove Conversation Users',

    topicStudentEvaluationList:   '[TOPIC STUDENT EVALUATION] Topic Student Evaluation List',
    topicStudentEvaluationRemove: '[TOPIC STUDENT EVALUATION] Remove Topic Student Evaluation List',
    topicStudentEvaluationNew:    '[TOPIC STUDENT EVALUATION] New Topic Student Evaluation',
    topicStudentEvaluationBlock:  '[TOPIC STUDENT EVALUATION] Block Topic Student Evaluation',
    topicStudentEvaluationLoad:   '[TOPIC STUDENT EVALUATION] Topic Student Evaluation Load',
    topicStudentEvaluationStop:   '[TOPIC STUDENT EVALUATION] Topic Student Evaluation Stop',

}